server:
  port: 8221 

debug: false

logging:
  level:
    id.co.fif.fema: debug
    com.indivaragroup.basic.cache: debug
    com.hazelcast: debug
    org.springframework: info
    org.springframework.test: info
  config: classpath:log4j2.xml

spring:
    hazelcast:
        config: basic-hazelcast-default.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        password: 12345678Aa
        url: jdbc:postgresql://localhost:5432/credential_service
        username: credential_service
        # password: password
        # url: jdbc:postgresql://10.11.1.10:5432/credential_service
        # username: credential_service
        hikari:
          maximum-pool-size: 10
          connection-test-query: select 1
          idle-timeout: 120000

    jackson:
        serialization:
            write-dates-as-timestamps: true
        default-property-inclusion: non-null 
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

event:
  management:
    distributor:
      threadPoolQueueSize: 200000

hystrix:
  command:
    default:
      execution:
        isolation: 
          thread:
            timeoutInMilliseconds: 1200000


