server:
  port: 8080 

debug: false

logging:
  level:
    id.co.fif.fema: debug
    org.springframework: info
    org.springframework.test: info
  config: classpath:log4j2.xml

spring:
    hazelcast:
      config: fema-hazelcast-local.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        password: 12345678Aa
        url: jdbc:postgresql://femadb-dev.fifgroup.co.id:5432/report_service
        username: report_service
#        password: aA87654321
#        url: jdbc:postgresql://femadb-dev.fifgroup.co.id:5432/report_service_sit
#        username: report_service_sit
        hikari:
          maximum-pool-size: 10
          connection-test-query: select 1
          idle-timeout: 120000

    jackson:
        serialization:
            write-dates-as-timestamps: true
        default-property-inclusion: non-null 
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



