server:
  port: 0 

debug: false

logging:
  level:
    id.co.fif.fema: debug
    org.springframework: info
    org.springframework.test: info
  config: classpath:log4j2.xml

spring:
    hazelcast:
      config: basic-hazelcast-default.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        password: 12345678Aa
        url: jdbc:postgresql://localhost:5432/notification_service
        username: notification_service
        hikari:
          maximum-pool-size: 10
          connection-test-query: select 1
          idle-timeout: 120000

    jackson:
        serialization:
            write-dates-as-timestamps: true
        default-property-inclusion: non-null 
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false  

    mail:
      host: smtp.gmail.com
      port: 587
      username: kitonus@gmail.com
      password: ENC(AGkQkF826pKNmTrE5qAjFCufE3aKJTHP)
      properties:
        mail.smtp.auth: true
        mail.smtp.host: smtp.gmail.com
        mail.smtp.port: 587
        mail.smtp.starttls.enable: true
      
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#firebase.serverkey: AAAA99SOkYE:APA91bEP-kJdPBp25s4PY-6tvHRC1BT3j-3DdwP41gcSBBNLvTsW3QpSj6VxIrPHXuYurmwDVYddcA6IXyqyaTSd0rQUnjGExDZHevDkXFWamtU7EphwJ8BuBIA1aHXpXaoET7QrbHbN

firebase.serverkey: AAAAAWYgiP4:APA91bGzSLqY0bAFiuB4V9O3h13Tw75r-abRSzkzlQZLeuVb7HpVVo6CWwOYCtKAjC262bkVjZDljJRbCtdRohnUiMZhxyfpS2f3q7jUcmo68YKVl6sLaoLkjtn5g-90PaiPWlk-1hBm

