server:
  port: 0 

debug: false

logging:
  level:
    com.indivaragroup: debug
    org.springframework: info
    org.springframework.test: info
  config: classpath:log4j2.xml

spring:
    hazelcast:
      config: basic-hazelcast-default.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/fema_video_service
        username: fema_video_service
        hikari:
          maximum-pool-size: 10
          connection-test-query: select 1
          idle-timeout: 120000

    jackson:
        serialization:
            write-dates-as-timestamps: true
        default-property-inclusion: non-null 
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

event:
  management:
    distributor:
      threadPoolQueueSize: 200000
      
fema.video.player.token: 5db8cbfd4249ee5c43e753f79d6ed4afcf206a84f5775c4f59b839a095c4d74b

